logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: ERROR
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include:
        - beans
        - env
        - health
        - heapdump
        - info
        - mappings
        - metrics
        - sessions
        - shutdown
        - threaddump
server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: true
    basedir: tomcat
spring:
  application:
    name: alawal-easp-mclient
  main:
    allow-bean-definition-overriding: true
    banner-mode: log
    log-startup-info: false
  output:
    ansi:
      enabled: always